"""add image column to Doctor model

Revision ID: 2d5a721e2ae7
Revises: a57e0eae02d7
Create Date: 2024-07-10 12:37:06.817031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5a721e2ae7'
down_revision = 'a57e0eae02d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
