"""add specialisation column to doctors table

Revision ID: f2ca38e142a2
Revises: c85e46bdb53b
Create Date: 2024-07-09 19:50:19.271572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ca38e142a2'
down_revision = 'c85e46bdb53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
