"""adding password column

Revision ID: 985a58fed417
Revises: 850bdde185d3
Create Date: 2024-07-11 10:22:40.599293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985a58fed417'
down_revision = '850bdde185d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
